-- Fix appointments foreign key to reference profiles instead of auth.users
-- This allows PostgREST to detect the relationship for joins

-- Drop the old constraint (default name generated by Postgres)
ALTER TABLE appointments 
DROP CONSTRAINT appointments_user_id_fkey;

-- Add new constraint referencing profiles
ALTER TABLE appointments 
ADD CONSTRAINT appointments_user_id_fkey 
FOREIGN KEY (user_id) 
REFERENCES profiles(id) 
ON DELETE CASCADE;
